---
title: "Mercado mundial de videojuegos - Introducci칩n"
format: html
---

## Planteamiento del problema y preguntas de an치lisis

Se dispone de un conjunto de datos de ventas recopilado por una tienda de videojuegos. La empresa busca comprender el comportamiento del mercado en relaci칩n con los g칠neros de los juegos, las plataformas en las que fueron desarrollados, las diferencias entre regiones del mundo y la evoluci칩n de los lanzamientos a lo largo del tiempo.

El objetivo es realizar un an치lisis que proporcione informaci칩n suficiente a los responsables de la gesti칩n y administraci칩n de la tienda para responder preguntas clave como:

- 쮺u치l es el comportamiento de los lanzamientos de juegos por a침o?
- 쯈u칠 tan diferentes son las ventas entre plataformas y c칩mo var칤an en el tiempo?
- 쯈u칠 plataformas son m치s populares y c칩mo evoluciona su popularidad?
- 쮺u치l es el ciclo de vida de una plataforma de videojuegos?
- 쮺u치les son las plataformas l칤deres del mercado y cu치les podr칤an ser rentables en el futuro?
- 쯃as rese침as de los usuarios influyen en las ventas de videojuegos?
- 쮺u치les son los g칠neros de videojuegos m치s rentables?
- 쮺칩mo se comporta el mercado en cada regi칩n respecto a plataformas y g칠neros?
- 쮼xisten diferencias en las calificaciones promedio de los usuarios entre Xbox One y PC?
- 쮼xisten diferencias en las calificaciones promedio de los g칠neros Acci칩n y Deportes?

Al finalizar el an치lisis, los interesados deber치n contar con el conocimiento suficiente sobre el comportamiento del mercado para tomar decisiones estrat칠gicas acertadas en relaci칩n con las ventas del a침o siguiente.


游녤 [Ver an치lisis completo](tripleten_videogames_case.qmd)
